import type { GameCardResponse } from "./types";

// ESA fixture data — SOURCE: statistics extracted verbatim from the approved
// interactive prototype `esa-broncos-chiefs-four-view-game-card.html`
// (Denver at Kansas City, final score Denver 10, Kansas City 31).
//
// This is NOT official NFL gamebook data. recordStatus is "preliminary" and
// gamebookVerified is false until the official gamebook is reconciled and
// verification passes — see ESA_CLAUDE_CODE_HANDOFF.md and the ESA pipeline
// design (Record of Truth / ITQAN quality control) for what "verified" means.
export const sampleGameCard: GameCardResponse = {
  schemaVersion: "1.0",
  gameId: "esa-2026-den-at-kc-prototype-v1",
  recordVersion: "prototype-extract-1.0",
  recordStatus: "preliminary",
  generatedAtUtc: "2026-09-15T00:00:00.000Z",
  dataQualityScore: 0.55,
  gamebookVerified: false,
  game: {
    date: "2026-10-11",
    week: 6,
    status: "FINAL",
    away: {
      teamId: "DEN",
      name: "Denver",
      abbreviation: "DEN",
      slug: "denver-broncos",
      score: 10,
      primaryColorToken: "denver-blue",
      secondaryColorToken: "denver-blue-lt",
    },
    home: {
      teamId: "KC",
      name: "Kansas City",
      abbreviation: "KC",
      slug: "kansas-city-chiefs",
      score: 31,
      primaryColorToken: "chiefs-red",
      secondaryColorToken: "chiefs-red-lt",
    },
  },
  analyses: [
    {
      teamId: "DEN",
      unit: "offense",
      thesis: "Denver’s offense could not sustain possessions or create enough scoring opportunities.",
      primaryFinding: "Denver turned 12 possessions into only 10 points.",
      primaryMetricIds: ["den-off-points-per-possession"],
      metrics: [
        {
          metricId: "den-off-points-per-possession",
          label: "Points per possession",
          coachingLabel: "Possession production",
          unit: "pts/possession",
          value: 0.83,
          formattedValue: "0.83",
          validationStatus: "passed",
          lineageId: "lineage-den-off-ppp-v1",
        },
        {
          metricId: "den-off-yards-per-play",
          label: "Yards per play",
          coachingLabel: "Stay on the field",
          unit: "yds/play",
          value: 3.7,
          formattedValue: "3.7",
          validationStatus: "passed",
          lineageId: "lineage-den-off-ypp-v1",
        },
        {
          metricId: "den-off-third-down",
          label: "Third down conversions",
          coachingLabel: "Stay on the field",
          unit: "conversions",
          value: "2/12",
          formattedValue: "2/12",
          validationStatus: "passed",
          lineageId: "lineage-den-off-3rd-v1",
        },
        {
          metricId: "den-off-chunk-yards",
          label: "Chunk yards",
          coachingLabel: "Create chunk gains",
          unit: "yards",
          value: 36,
          formattedValue: "36",
          validationStatus: "passed",
          lineageId: "lineage-den-off-chunk-v1",
        },
      ],
      findings: [
        {
          findingId: "den-off-f01",
          title: "Stay on the field",
          shortEvidence: "2/12 third down",
          evidence: "Denver converted only 16.7% of third downs.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "den-off-f02",
          title: "Create chunk gains",
          shortEvidence: "36 yards",
          evidence: "Denver produced only two gains of at least 15 yards.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "den-off-f03",
          title: "Finish scoring opportunities",
          shortEvidence: "1 red-zone TD",
          evidence: "Denver reached the red zone twice and scored one touchdown.",
          evidenceGrade: "B",
          controllability: "partial",
          publicationStatus: "published",
        },
      ],
      priorities: [
        {
          priority: 1,
          title: "Win first and second down",
          practiceMeasure: "Create manageable third downs.",
          gameMeasure: "Third-down distance under 5 yards.",
          evidenceFindingIds: ["den-off-f01"],
        },
        {
          priority: 2,
          title: "Create two chunk gains per half",
          practiceMeasure: "Reduce the number of perfect plays required.",
          gameMeasure: "2+ gains of 15+ yards per half.",
          evidenceFindingIds: ["den-off-f02"],
        },
        {
          priority: 3,
          title: "Finish red-zone possessions",
          practiceMeasure: "Turn trips into touchdowns.",
          gameMeasure: "Red-zone TD rate above 50%.",
          evidenceFindingIds: ["den-off-f03"],
        },
      ],
    },
    {
      teamId: "DEN",
      unit: "defense",
      thesis: "Denver’s defense could not stop Kansas City’s run-driven control or end possessions.",
      primaryFinding: "Kansas City rushed for 220 yards; Kenneth Walker produced 173.",
      primaryMetricIds: ["den-def-rush-yards-allowed"],
      metrics: [
        {
          metricId: "den-def-rush-yards-allowed",
          label: "Rush yards allowed",
          coachingLabel: "Stop the run early",
          unit: "yards",
          value: 220,
          formattedValue: "220",
          validationStatus: "passed",
          lineageId: "lineage-den-def-rush-v1",
        },
        {
          metricId: "den-def-opponent-lead-rusher-yards",
          label: "Opponent lead-rusher yards",
          coachingLabel: "Stop the run early",
          unit: "yards",
          value: null,
          formattedValue: "Unavailable",
          validationStatus: "unavailable",
          lineageId: null,
        },
        {
          metricId: "den-def-opponent-lead-rusher-ypc",
          label: "Opponent lead-rusher yards per carry",
          coachingLabel: "Stop the run early",
          unit: "yds/carry",
          value: 7.5,
          formattedValue: "7.5",
          validationStatus: "passed",
          lineageId: "lineage-den-def-ypc-v1",
        },
        {
          metricId: "den-def-third-down-allowed",
          label: "Third down allowed",
          coachingLabel: "Stay on the field",
          unit: "conversions",
          value: "9/17",
          formattedValue: "9/17",
          validationStatus: "passed",
          lineageId: "lineage-den-def-3rd-v1",
        },
      ],
      findings: [
        {
          findingId: "den-def-f01",
          title: "Stop the run early",
          shortEvidence: "220 yards",
          evidence: "Kansas City controlled downs and drives on the ground.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "den-def-f02",
          title: "Eliminate explosive-run exits",
          shortEvidence: "60-yard TD",
          evidence: "Without Walker’s 60-yard touchdown, he still averaged 5.1 per carry.",
          evidenceGrade: "B",
          controllability: "partial",
          publicationStatus: "published",
        },
        {
          findingId: "den-def-f03",
          title: "Get off the field",
          shortEvidence: "9/17 third down",
          evidence: "Kansas City converted 52.9% of third downs.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "den-def-f04",
          title: "Validate fits and tackling",
          shortEvidence: "Film required",
          evidence: "All-22 is needed to assign gap, leverage and tackling responsibility.",
          evidenceGrade: "D",
          controllability: "uncontrollable",
          publicationStatus: "withheld",
        },
      ],
      priorities: [
        {
          priority: 1,
          title: "Allow no runs of 15+ yards",
          practiceMeasure: "Protect edges and pursuit leverage.",
          gameMeasure: "Zero explosive runs allowed.",
          evidenceFindingIds: ["den-def-f01", "den-def-f02"],
        },
        {
          priority: 2,
          title: "Hold early-down runs below four",
          practiceMeasure: "Force third-and-7-plus.",
          gameMeasure: "Average early-down rush under 4 yards.",
          evidenceFindingIds: ["den-def-f01"],
        },
        {
          priority: 3,
          title: "Grade every Walker carry",
          practiceMeasure: "Audit assignment, fit, first contact and finish.",
          gameMeasure: "Complete all-22 review filed within 48 hours.",
          evidenceFindingIds: ["den-def-f04"],
        },
      ],
    },
    {
      teamId: "KC",
      unit: "offense",
      thesis: "Kansas City’s offense won with run control, sustained possessions and chunk gains.",
      primaryFinding: "Kansas City turned 12 possessions into 31 points.",
      primaryMetricIds: ["kc-off-points-per-possession"],
      metrics: [
        {
          metricId: "kc-off-points-per-possession",
          label: "Points per possession",
          coachingLabel: "Possession production",
          unit: "pts/possession",
          value: 2.58,
          formattedValue: "2.58",
          validationStatus: "passed",
          lineageId: "lineage-kc-off-ppp-v1",
        },
        {
          metricId: "kc-off-rush-yards",
          label: "Rush yards",
          coachingLabel: "Stop the run early",
          unit: "yards",
          value: 220,
          formattedValue: "220",
          validationStatus: "passed",
          lineageId: "lineage-kc-off-rush-v1",
        },
        {
          metricId: "kc-off-third-down",
          label: "Third down conversions",
          coachingLabel: "Stay on the field",
          unit: "conversions",
          value: "9/17",
          formattedValue: "9/17",
          validationStatus: "passed",
          lineageId: "lineage-kc-off-3rd-v1",
        },
        {
          metricId: "kc-off-chunk-yards",
          label: "Chunk yards",
          coachingLabel: "Create chunk gains",
          unit: "yards",
          value: 181,
          formattedValue: "181",
          validationStatus: "passed",
          lineageId: "lineage-kc-off-chunk-v1",
        },
      ],
      findings: [
        {
          findingId: "kc-off-f01",
          title: "Run the engine",
          shortEvidence: "220 yards",
          evidence: "Kenneth Walker rushed for 173 yards at 7.5 per carry.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "kc-off-f02",
          title: "Stay on the field",
          shortEvidence: "9/17 third down",
          evidence: "Kansas City extended possessions at a 52.9% rate.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "kc-off-f03",
          title: "Create chunk gains",
          shortEvidence: "181 yards",
          evidence: "Five gains of at least 15 yards compressed the field.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "kc-off-f04",
          title: "Convert leverage",
          shortEvidence: "31 points",
          evidence: "Kansas City produced 2.58 points per possession.",
          evidenceGrade: "B",
          controllability: "partial",
          publicationStatus: "published",
        },
      ],
      priorities: [
        {
          priority: 1,
          title: "Preserve run efficiency",
          practiceMeasure: "Keep early downs favorable.",
          gameMeasure: "Maintain 5+ yards per carry.",
          evidenceFindingIds: ["kc-off-f01"],
        },
        {
          priority: 2,
          title: "Maintain third-down answers",
          practiceMeasure: "Protect possession continuity.",
          gameMeasure: "Hold third-down conversion above 45%.",
          evidenceFindingIds: ["kc-off-f02"],
        },
        {
          priority: 3,
          title: "Keep creating explosives",
          practiceMeasure: "Generate field without adding play volume.",
          gameMeasure: "2+ chunk gains per half.",
          evidenceFindingIds: ["kc-off-f03"],
        },
      ],
    },
    {
      teamId: "KC",
      unit: "defense",
      thesis: "Kansas City’s defense restricted Denver’s efficiency, possessions and explosive-play supply.",
      primaryFinding: "Kansas City’s defense held Denver to 0.83 points per possession while its offense produced 2.58.",
      primaryMetricIds: ["kc-def-points-allowed"],
      metrics: [
        {
          metricId: "kc-def-points-allowed",
          label: "Points allowed",
          coachingLabel: "Finish scoring opportunities",
          unit: "points",
          value: 10,
          formattedValue: "10",
          validationStatus: "passed",
          lineageId: "lineage-kc-def-pts-v1",
        },
        {
          metricId: "kc-def-yards-allowed",
          label: "Yards allowed",
          coachingLabel: "Stop the run early",
          unit: "yards",
          value: 176,
          formattedValue: "176",
          validationStatus: "passed",
          lineageId: "lineage-kc-def-yds-v1",
        },
        {
          metricId: "kc-def-third-down-allowed",
          label: "Third down allowed",
          coachingLabel: "Stay on the field",
          unit: "conversions",
          value: "2/12",
          formattedValue: "2/12",
          validationStatus: "passed",
          lineageId: "lineage-kc-def-3rd-v1",
        },
        {
          metricId: "kc-def-takeaways",
          label: "Takeaways",
          coachingLabel: "Create chunk gains",
          unit: "takeaways",
          value: 2,
          formattedValue: "2",
          validationStatus: "passed",
          lineageId: "lineage-kc-def-takeaways-v1",
        },
      ],
      findings: [
        {
          findingId: "kc-def-f01",
          title: "End possessions",
          shortEvidence: "2/12 allowed",
          evidence: "Denver converted only 16.7% on third down.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "kc-def-f02",
          title: "Prevent chunk gains",
          shortEvidence: "36 yards allowed",
          evidence: "Denver produced only two 15+ yard scrimmage plays.",
          evidenceGrade: "A",
          controllability: "high",
          publicationStatus: "published",
        },
        {
          findingId: "kc-def-f03",
          title: "Create takeaways",
          shortEvidence: "2",
          evidence: "Kansas City generated two Denver giveaways.",
          evidenceGrade: "B",
          controllability: "partial",
          publicationStatus: "published",
        },
        {
          findingId: "kc-def-f04",
          title: "Turn defense into points",
          shortEvidence: "14 points",
          evidence: "The offense scored 14 points following Denver turnovers.",
          evidenceGrade: "B",
          controllability: "partial",
          publicationStatus: "published",
        },
      ],
      priorities: [
        {
          priority: 1,
          title: "Keep third-down pressure",
          practiceMeasure: "Continue ending possessions.",
          gameMeasure: "Hold third-down allowed below 30%.",
          evidenceFindingIds: ["kc-def-f01"],
        },
        {
          priority: 2,
          title: "Protect explosive-play limits",
          practiceMeasure: "Force Denver to execute long sequences.",
          gameMeasure: "Allow 3 or fewer chunk gains.",
          evidenceFindingIds: ["kc-def-f02"],
        },
        {
          priority: 3,
          title: "Preserve takeaway leverage",
          practiceMeasure: "Create short fields without gambling away structure.",
          gameMeasure: "1+ takeaway per game.",
          evidenceFindingIds: ["kc-def-f03"],
        },
      ],
    },
  ],
};
